<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE relacion [
<!ELEMENT relacion (persona)+>
<!ELEMENT persona (nombre,email*, parentesco?)>
<!ATTLIST persona carnet ID #REQUIRED>
<!ATTLIST persona sexo (hombre|mujer) #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT parentesco EMPTY>
<!ATTLIST parentesco tutor-legal IDREFS #IMPLIED hermano-a IDREFS #IMPLIED>
]>

<relacion>
<persona carnet="id80154636G" sexo="hombre">
    <nombre>Ricardo Borriquero Conejo</nombre>
    <email>ricadobdc@gmailcom</email>
</persona>
<persona carnet="id35876524h" sexo="mujer">
    <nombre>Mar√≠a Conejo Rosado</nombre>
    <email>mariacr@gmailcom</email>
    <parentesco tutor-legal="id80154636G"/>
</persona>
<persona carnet="id65876524h" sexo="hombre">
    <nombre>Carlos Borriquero Conejo</nombre>
    <email>carlos@gmailcom</email>
    <parentesco hermano-a="id80154636G"/>
</persona>
</relacion>