<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE errores [
<!ELEMENT errores (error+)>
<!ELEMENT error (codigo, tipo, descripcion, actividad, fecha_hora, nlinea, ncolumna )>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT tipo (AVISO|WARNING|FATAL)>
<!ELEMENT AVISO EMPTY>
<!ELEMENT WARNING EMPTY>
<!ELEMENT FATAL EMPTY>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT actividad (#PCDATA)>
<!ELEMENT fecha_hora (#PCDATA)>
<!ELEMENT nlinea (#PCDATA)>
<!ELEMENT ncolumna (#PCDATA)>
<!ATTLIST error id ID #REQUIRED>
]>
<errores>
    <error id="_1">
        <codigo>01</codigo>
        <tipo><FATAL/></tipo>
        <descripcion>Falta el campo "ciudad"</descripcion>
        <actividad>Ejemplo13.xml</actividad>
        <fecha_hora>17/02/2020 - 9:30</fecha_hora>
        <nlinea>16</nlinea>
        <ncolumna>12</ncolumna>
    </error>
    <error id="_2">
        <codigo>02</codigo>
        <tipo><FATAL/></tipo>
        <descripcion>En la inserción de datos falta el nodo raíz "agenda"</descripcion>
        <actividad>Ejemplo14.xml</actividad>
        <fecha_hora>17/02/2020 - 9:37</fecha_hora>
        <nlinea>9</nlinea>
        <ncolumna>1</ncolumna>
    </error>
    <error id="_3">
        <codigo>03</codigo>
        <tipo><FATAL/></tipo>
        <descripcion>Falta el atributo id de persona.</descripcion>
        <actividad>Ejemplo14.xml</actividad>
        <fecha_hora>17/02/2020 - 9:39</fecha_hora>
        <nlinea>10</nlinea>
        <ncolumna>10</ncolumna>
    </error>
        <error id="_4">
        <codigo>04</codigo>
        <tipo><FATAL/></tipo>
        <descripcion>El campo "tw" no se encuentra definido para nuestro elemento.</descripcion>
        <actividad>Ejemplo14.xml</actividad>
        <fecha_hora>17/02/2020 - 9:41</fecha_hora>
        <nlinea>17</nlinea>
        <ncolumna>9</ncolumna>
    </error>
</errores>

<!-- Ejercicio de señalamiento de los errores de las actividades del tema. -->
<!-- Ejemplo 13 -->